name: Mobile fastlane release workflow
on:
  push:
    branches: [mobile-fastlane-ci-cd]
  workflow_dispatch:

jobs:
  build-mobile:
    name: build-mobile
    runs-on: macos-latest #orai-self-hosted
    strategy:
      matrix:
        node-version: [16.14.0]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # - uses: sonarsource/sonarqube-scan-action@master
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Checkout submodule repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      # # Update references
      # - name: Git Submodule Update
      #   working-directory: packages/background
      #   run: |
      #     git checkout feat/link-gg
      - name: Install dependencies # install project deps with --frozen-lockfile to make sure we will have the same packages version ( very recommended  on running yarn install on ci)
        run: yarn install --frozen-lockfile
      - name: Install mobile packages
        working-directory: packages/mobile
        run: yarn --silent
      - name: Build Libs
        run: yarn build:libs
      - name: Build provider
        working-directory: packages/mobile
        run: yarn build:provider
        env:
          CI: false
      - name: Setup Ruby 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.10
          bundler-cache: true
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        working-directory: packages/mobile/android
        run: chmod +x gradlew
      - name: Setup Fastlane android
        working-directory: packages/mobile/android/fastlane
        run: cd .. && bundle update && fastlane beta
        env:
          JSON_KEY_DATA: ${{ secrets.GOOGLE_ACCOUNT_SERVICE }}
          DISCORD_HOOK: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          ALIAS: ${{ secrets.ALIAS }}
          PASS_KEY_STORE: ${{ secrets.PASS_KEY_STORE }}
          PASS_ALIAS_KEY_STORE: ${{ secrets.PASS_KEY_STORE }}
          FILE_PATH: "/OWalletKeystore"
      # - name: Setup Fastlane android
      #   working-directory: packages/mobile/android/fastlane
      #   run: cd .. && bundle update && fastlane beta
      #   env:
      #     JSON_KEY_DATA: ${{ secrets.GOOGLE_ACCOUNT_SERVICE }}
      #     DISCORD_HOOK: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
      #     ALIAS: ${{ secrets.ALIAS }}
      #     PASS_KEY_STORE: ${{ secrets.PASS_KEY_STORE }}
      #     PASS_ALIAS_KEY_STORE: ${{ secrets.PASS_KEY_STORE }}
      #     FILE_PATH: "/OWalletKeystore"
        # working-directory: packages/mobile/android/fastlane
        
      # - name: Deploy on AppCenter
      #   working-directory: packages/mobile
      #   run: |
      #     yarn code-push-android --token ${{ secrets.CODEPUSH_TOKEN }} --description "${{ github.event.head_commit.message }}"
      #     yarn code-push-ios --token ${{ secrets.CODEPUSH_TOKEN }} --description "${{ github.event.head_commit.message }}"
      
      # - name: Send discord message
      #   uses: appleboy/discord-action@master
      #   with:
      #     webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
      #     webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
      #     username: "GitBot"
      #     message: Fastlane success! Comment=${{ github.event.head_commit.message }}

      # - name: Send discord message
      #   if: ${{ failure() }}
      #   uses: appleboy/discord-action@master
      #   with:
      #     webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
      #     webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
      #     username: "GitBot"
      #     message: Fastlane fail ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
  # release-android:
  #   needs: 
  #   - build-mobile
  #   runs-on: ubuntu-latest #orai-self-hosted
  #   steps:
  #     - run: echo "The workflow is now ready to test your code."
  #     - name: Grant execute permission for gradlew
  #       working-directory: packages/mobile/android
  #       run: chmod +x gradlew
  #     - name: Setup Fastlane android
  #       working-directory: packages/mobile/android/fastlane
  #       run: cd .. && bundle update && fastlane beta
  #       env:
  #         JSON_KEY_DATA: ${{ secrets.GOOGLE_ACCOUNT_SERVICE }}
  #         DISCORD_HOOK: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
  #         ALIAS: ${{ secrets.ALIAS }}
  #         PASS_KEY_STORE: ${{ secrets.PASS_KEY_STORE }}
  #         PASS_ALIAS_KEY_STORE: ${{ secrets.PASS_KEY_STORE }}
  #         FILE_PATH: "/OWalletKeystore"

  # # release-ios:
  #   needs: 
  #   - build-mobile
  #   runs-on: macos-latest #orai-self-hosted
  #   steps:
  #     - name: Install IOS Dependencies
  #       working-directory: packages/mobile/
  #       run: yarn pod:install --silent
  #     - name: Setup Fastlane ios
  #       working-directory: packages/mobile/android/fastlane
  #       run: cd .. && bundle update && fastlane beta
  #       env:
  #         JSON_KEY_DATA: ${{ secrets.GOOGLE_ACCOUNT_SERVICE }}
  #         DISCORD_HOOK: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
  #         ALIAS: ${{ secrets.ALIAS }}
  #         PASS_KEY_STORE: ${{ secrets.PASS_KEY_STORE }}
  #         PASS_ALIAS_KEY_STORE: ${{ secrets.PASS_KEY_STORE }}
  #         FILE_PATH: "/OWalletKeystore"